spring:
  datasource:
    url: jdbc:mysql://localhost:3306/map?serverTimezone=Asia/Seoul
    username: asazulang33
    password: qwerasdf123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  application:
    name: USER-SERVICE